### ISSUE TITLE
MongoDB CE Stateful Set doesn't initialize/start

### ISSUE THREAD

**Issue by arne-fuchs** [ibm-watson-iot/iot-docs#21]
The installation script for mongodb does run through successfully until the point it waits until the stateful set is initialize or started.

The openshift events log says at the total beginning:

`0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.`

And after some successful logs it finally throws the error:

`Readiness probe failed: panic: couldn't open sink "/var/log/mongodb-mms-automation/readiness.log": open /var/log/mongodb-mms-automation/readiness.log: permission denied goroutine 1 [running]: main.main() /build/main.go:216 +0x2df `

The logs are as followed:
`2022-08-04T11:41:03.010Z	INFO	versionhook/main.go:34	Running version change post-start hook
2022-08-04T11:41:03.010Z	INFO	versionhook/main.go:41	Waiting for agent health status...
2022-08-04T11:41:04.011Z	ERROR	versionhook/main.go:49	Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
	/go/cmd/versionhook/main.go:49
runtime.main
	/usr/local/go/src/runtime/proc.go:225
`

The persistent volumes does exist as well as the persistent volumes claims. If I shell into the container the following path is available:
`/var/log/mongodb-mms-automation/healthstatus`
All folders, no files. The permissions are set correctly.

Running OpenShift 4.8.46

I am running out of options, thanks for the help!

**Comment by arne-fuchs** [comment]
Also tried the version from the pr: https://github.com/ibm-watson-iot/iot-docs/pull/20
Same results

**Comment by arne-fuchs** [comment]
Changed MONGODB_STORAGE_CLASS=ibmc-file-gold -> MONGODB_STORAGE_CLASS=ibmc-block-gold and it worked now.
